### ISSUE TITLE
Rename the <button> tag to avoid all confusion with the real html

### ISSUE THREAD

**Issue by alekart** [alekart/grunt-marker#4]
Maybe the `<button>` tag should be renamed into something inexistant in the HTML.
Here are some possibilities:
- btn
- mail-button
- sbutton (Super Button :D)
- bbutton (~~Batman~~ Bulletproof Button)
- bp-button (Bullet Proof Button)
- bpbutton (Bullet Proof Button)
- ~~bouton~~

**Comment by sire-sam** [comment]
`<btn-vml>` ?

**Comment by alekart** [comment]
Changed in v0.2.0. 
**ATTENTION** this update is breaking as it will not transform `button` tag anymore.
